name: pam-authenticate
version: 0.1.0.0

synopsis: App for checking a user password with PAM.

description: >
  A small command-line app demonstrating checking a user password with PAM.

stability: alpha
category: System

executables:
  pam-authenticate:
    source-dirs: app
    main: Main.hs

dependencies:
  - base >= 4 && < 5
  - haskeline
  - mtl
  - optparse-applicative
  - optparse-generic
  - pam
  - text
  - transformers

ghc-options: -Wall
default-extensions: NoImplicitPrelude

github: chris-martin/pam
maintainer: Chris Martin
copyright: Copyright (c) 2017 Chris Martin
license: BSD3
license-file: LICENSE
